### ISSUE TITLE
Questionário direcionado a não usuários.

### ISSUE THREAD

**Issue by mlfaa** [Instagram-Requisitos-2018-1/Instagram#1]
Sugestões do grupo: 
* [x] Se já conhece o Instagram (caso a resposta seja negativa, pergunta se o usuário tem ideia do que o Instagram faz)
* [x] Se utiliza alguma outra aplicação
* [x] Pergunta aberta: Motivo da não utilização do Instagram.

**Comment by nahmrodrigues** [comment]
Utilizar material disponibilizado na plataforma aprender.

[Standardized Usability Questionnaires](https://www.safaribooksonline.com/library/view/quantifying-the-user/9780123849687/xhtml/CHP008.html)
