### ISSUE TITLE
Questionário direcionado a usuários.

### ISSUE THREAD

**Issue by mlfaa** [Instagram-Requisitos-2018-1/Instagram#2]
Tarefas:

* [x] Pergunta aberta (sugestão de melhoria do usuário)
* [ ] Melhorar as perguntas já feitas
* [ ] Tirar perguntas com ideias repetidas

**Comment by nahmrodrigues** [comment]
Otimizar o formulário utilizando material disponibilizado na plataforma aprender.

[Standardized Usability Questionnaires](https://www.safaribooksonline.com/library/view/quantifying-the-user/9780123849687/xhtml/CHP008.html)
