### ISSUE TITLE
Refatoração do Moscow

### ISSUE THREAD

**Issue by mlfaa** [Instagram-Requisitos-2018-1/Instagram#9]
Tarefas:
* [x] Melhorar o visual Moscow
* [x] Separar em grupos (por exemplo, postagens, interação, etc)
* [x] Destrinchar as funcionalidades

**Comment by mlfaa** [comment]
Utilizar verbos nas funcionalidades, exemplo: realizar postagem, editar postagem, etc...

**Comment by andrewlucasgs** [comment]
Criei a pagina do Moscow na wiki, e já coloquei algumas funcionalidades lá.

[Moscow](https://github.com/Instagram-Requisitos-2018-1/Instagram/wiki/MoSCoW)

**Comment by gabrielademoraes** [comment]
Adicionei algumas funcionalidades na parte do Direct.

**Comment by gabrielademoraes** [comment]
Destrinchei algumas funcionalidades e adicionei novos tópicos.

**Comment by LucasPenido** [comment]
Dei uma restruturada na divisão e adicionei algumas funcionalidades
